### ISSUE TITLE
Cannot run the pattern-review tool

### ISSUE THREAD

**Issue by chris-grove** [obophenotype/pattern-review#7]
@matentzn 
Here's the command I run and the error message that follows:

```
$ docker run -p 8050:8050 --env-file ./env.list obolibrary/patternreview
Traceback (most recent call last):
  File "app.py", line 357, in <module>
    df = get_pattern_table()
  File "app.py", line 234, in get_pattern_table
    rows_list.append(create_overview_table_row(content_file))
  File "app.py", line 212, in create_overview_table_row
    yaml_content = yaml.round_trip_load(contents,preserve_quotes=True)
  File "/usr/local/lib/python3.5/site-packages/ruamel/yaml/main.py", line 1000, in round_trip_load
    return load(stream, RoundTripLoader, version, preserve_quotes=preserve_quotes)
  File "/usr/local/lib/python3.5/site-packages/ruamel/yaml/main.py", line 935, in load
    return loader._constructor.get_single_data()
  File "/usr/local/lib/python3.5/site-packages/ruamel/yaml/constructor.py", line 109, in get_single_data
    node = self.composer.get_single_node()
  File "/usr/local/lib/python3.5/site-packages/ruamel/yaml/composer.py", line 87, in get_single_node
    event.start_mark,
ruamel.yaml.composer.ComposerError: expected a single document in the stream
  in "<byte string>", line 2, column 1:
    This is a listing of all the pat ... 
    ^ (line: 2)
but found another document
  in "<byte string>", line 6, column 1:
    **
    ^ (line: 6)
```

**Comment by matentzn** [comment]
Great catch, thanks!

Should be fixed now:

run `docker pull obolibrary/patternreview` and continue as usual

**Comment by chris-grove** [comment]
Looks good! Thanks!
